<?php 


$helper = $this->helper('Magepow\Sizechart\Helper\Data');
$isEnabled =  $helper->getConfigModule('general/enabled'); 
if($isEnabled){
$isTextLinkDisplayed = $helper->getConfigModule('general/display_text');
$iconImage   = $helper->getConfigModule('general/image_icon');
$iconImageShow = $block->getMedia($iconImage);
 $productCollection = $block->getConfig(); 
 $typeDisplay = $productCollection['type_display'];
 $name = $productCollection['name'];
 $description = $productCollection['description'];
 $sizechartInfo = $productCollection['sizechart_info'];
  $currentProductId = $block->getCurrentProduct()->getId();
  $productArrayId = array($currentProductId);
 $_productCollection = $block->getLoadedProductCollection();

foreach ($_productCollection as $value) {
    $arrayProduct = $value->getData();
  if(array_intersect($productArrayId, $arrayProduct)){
    if($typeDisplay == 3){
  ?>
<div class="sizechart-custom">
      
         <h2 class="sizechart-name"><?php echo $name;?></h2>
        <div class="info">
            <p class="des"><?php echo $description; ?></p>

        </div>
        <div class="sizechart-digram">
            <?php echo $sizechartInfo;?>
        </div> 
 
</div>

<?php
}
}
}
}

?>