<?php 

$helper = $this->helper('Magepow\Sizechart\Helper\Data');

$isTextLinkDisplayed = $helper->getConfigModule('general/display_text');
$iconImage   = $helper->getConfigModule('general/image_icon');
$iconImageShow = $block->getMedia($iconImage);
$productCollection = $block->getConfig(); 
$typeDisplay = $productCollection['type_display'];
$name = $productCollection['name'];
$description = $productCollection['description'];
$sizechartInfo = $productCollection['sizechart_info'];
$currentProductId = $block->getCurrentProduct()->getId();
$productArrayId = array($currentProductId);
$_productCollection = $block->getLoadedProductCollection();

foreach ($_productCollection as $value) {
  $arrayProduct = $value->getData();
  if(array_intersect($productArrayId, $arrayProduct)){
    if($typeDisplay != 3) continue;
?>
    <div class="sizechart-custom">
        <h2 class="sizechart-name"><?php echo $name;?></h2>
        <div class="info">
            <div class="des"><?php echo $description; ?></div>
        </div>
        <div class="sizechart-digram">
            <?php echo $block->getContentFromStaticBlock($sizechartInfo);?>
        </div> 
    </div>
<?php
  }
}

?>