
<?php
$sizeChart = $block->getSizeChart();
// var_dump($sizeChart);die('sdf');
if(!$sizeChart) return;
$helper    = $this->helper('Magepow\Sizechart\Helper\Data');
$typeDisplay = $sizeChart->getData('type_display');
if($typeDisplay != 3) return;
$isTextLinkDisplayed = $helper->getConfigModule('general/display_text');
$iconImage   = $helper->getConfigModule('general/image_icon');
$iconImageShow = $block->getMedia($iconImage);
$name = $sizeChart->getData('name');
$description = $sizeChart->getData('description');
$sizechartInfo = $sizeChart->getData('sizechart_info');

?>
<div class="sizechart-custom">
  <h2 class="sizechart-name"><?php echo $name;?></h2>
  <div class="info">
      <div class="des"><?php echo $description; ?></div>
  </div>
  <div class="sizechart-digram">
      <?php echo $block->getContentFromStaticBlock($sizechartInfo);?>
  </div> 
</div>
